-- Database setup script for Data Catalog application
-- Creates catalog infrastructure and metadata tables
-- Deploys using SYSADMIN role

-- Create catalog database
CREATE DATABASE IF NOT EXISTS CATALOG_DB
COMMENT = 'Data Catalog application database';

-- Create catalog schema
CREATE SCHEMA IF NOT EXISTS CATALOG_DB.CATALOG_SCHEMA
COMMENT = 'Main schema for catalog tables and metadata';

-- ============================================================================
-- METADATA TABLES
-- ============================================================================

-- Table to store cached metadata from INFORMATION_SCHEMA
CREATE TABLE IF NOT EXISTS CATALOG_DB.CATALOG_SCHEMA.CATALOG_METADATA (
    DATABASE_NAME STRING NOT NULL,
    SCHEMA_NAME STRING NOT NULL,
    TABLE_NAME STRING NOT NULL,
    TABLE_TYPE STRING,
    ROW_COUNT NUMBER,
    BYTES NUMBER,
    CREATED TIMESTAMP_NTZ,
    LAST_ALTERED TIMESTAMP_NTZ,
    COMMENT STRING,
    CACHED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (DATABASE_NAME, SCHEMA_NAME, TABLE_NAME)
)
COMMENT = 'Cached table and view metadata from all databases';

-- Table to store column-level metadata
CREATE TABLE IF NOT EXISTS CATALOG_DB.CATALOG_SCHEMA.CATALOG_COLUMNS (
    FULL_TABLE_NAME STRING NOT NULL,
    COLUMN_NAME STRING NOT NULL,
    DATA_TYPE STRING,
    IS_NULLABLE STRING,
    COMMENT STRING,
    ORDINAL_POSITION NUMBER,
    PRIMARY KEY (FULL_TABLE_NAME, COLUMN_NAME)
)
COMMENT = 'Column-level metadata for all tables';

-- ============================================================================
-- USER-GENERATED CONTENT TABLES
-- ============================================================================

-- User ratings for tables (5-star system)
CREATE TABLE IF NOT EXISTS CATALOG_DB.CATALOG_SCHEMA.USER_RATINGS (
    TABLE_FULL_NAME STRING NOT NULL,
    USER_NAME STRING NOT NULL,
    RATING NUMBER NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (TABLE_FULL_NAME, USER_NAME)
)
COMMENT = 'User ratings for tables (1-5 stars)';

-- User comments and discussions
CREATE TABLE IF NOT EXISTS CATALOG_DB.CATALOG_SCHEMA.USER_COMMENTS (
    COMMENT_ID STRING DEFAULT UUID_STRING(),
    TABLE_FULL_NAME STRING NOT NULL,
    USER_NAME STRING NOT NULL,
    COMMENT_TEXT STRING NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (COMMENT_ID)
)
COMMENT = 'User comments and discussions for tables';

-- Wiki-style user documentation
CREATE TABLE IF NOT EXISTS CATALOG_DB.CATALOG_SCHEMA.TABLE_DESCRIPTIONS (
    TABLE_FULL_NAME STRING NOT NULL,
    USER_DESCRIPTION STRING,
    LAST_UPDATED_BY STRING,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (TABLE_FULL_NAME)
)
COMMENT = 'User-contributed wiki-style descriptions';

-- ============================================================================
-- ACCESS REQUEST WORKFLOW TABLES
-- ============================================================================

-- Access request tracking (for data access grants)
CREATE TABLE IF NOT EXISTS CATALOG_DB.CATALOG_SCHEMA.ACCESS_REQUESTS (
    REQUEST_ID STRING DEFAULT UUID_STRING(),
    TABLE_FULL_NAME STRING NOT NULL,
    REQUESTER STRING NOT NULL,
    JUSTIFICATION STRING NOT NULL,
    STATUS STRING DEFAULT 'pending',
    APPROVER STRING,
    DECISION_DATE TIMESTAMP_NTZ,
    DECISION_COMMENT STRING,
    REQUESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ACCESS_START_DATE DATE,
    ACCESS_END_DATE DATE,
    ACCESS_TYPE STRING DEFAULT 'ROLE',
    GRANT_TO_NAME STRING,
    ASSIGNED_TO STRING,
    ADDITIONAL_INFO STRING,
    PRIMARY KEY (REQUEST_ID)
)
COMMENT = 'Data access request workflow tracking';

-- ============================================================================
-- ROLE PERMISSIONS TABLE
-- ============================================================================

-- Table to store role-based permissions for catalog features
CREATE TABLE IF NOT EXISTS CATALOG_DB.CATALOG_SCHEMA.ROLE_PERMISSIONS (
    PERMISSION_ID STRING DEFAULT UUID_STRING(),
    SNOWFLAKE_ROLE STRING NOT NULL,
    PERMISSION_TYPE STRING NOT NULL,  -- APP_ACCESS, CREATE_REQUESTS, APPROVE_GLOSSARY, APPROVE_DATA_ACCESS, MANAGE_ROLES
    GRANTED_BY STRING,
    GRANTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PERMISSION_ID),
    UNIQUE (SNOWFLAKE_ROLE, PERMISSION_TYPE)
)
COMMENT = 'Role-based permissions for catalog features';

-- Insert default permissions for CATALOG_SERVICE_ROLE (all permissions)
INSERT INTO CATALOG_DB.CATALOG_SCHEMA.ROLE_PERMISSIONS (SNOWFLAKE_ROLE, PERMISSION_TYPE, GRANTED_BY)
SELECT 'CATALOG_SERVICE_ROLE', permission_type, 'SYSTEM'
FROM (
    SELECT 'APP_ACCESS' as permission_type UNION ALL
    SELECT 'CREATE_REQUESTS' UNION ALL
    SELECT 'APPROVE_GLOSSARY' UNION ALL
    SELECT 'APPROVE_DATA_ACCESS' UNION ALL
    SELECT 'MANAGE_ROLES'
) permissions
WHERE NOT EXISTS (
    SELECT 1 FROM CATALOG_DB.CATALOG_SCHEMA.ROLE_PERMISSIONS 
    WHERE SNOWFLAKE_ROLE = 'CATALOG_SERVICE_ROLE' AND PERMISSION_TYPE = permissions.permission_type
);

-- ============================================================================
-- BUSINESS GLOSSARY TABLES
-- ============================================================================

-- Global attribute definitions (e.g., "filing_type", "status")
CREATE TABLE IF NOT EXISTS CATALOG_DB.CATALOG_SCHEMA.ATTRIBUTE_DEFINITIONS (
    ATTRIBUTE_NAME STRING NOT NULL,
    DISPLAY_NAME STRING,
    DESCRIPTION STRING,
    CREATED_BY STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY STRING,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ATTRIBUTE_NAME)
)
COMMENT = 'Global business attribute definitions';

-- Enumerated values for attributes
CREATE TABLE IF NOT EXISTS CATALOG_DB.CATALOG_SCHEMA.ATTRIBUTE_ENUMERATIONS (
    ENUMERATION_ID STRING DEFAULT UUID_STRING(),
    ATTRIBUTE_NAME STRING NOT NULL,
    VALUE_CODE STRING NOT NULL,
    VALUE_DESCRIPTION STRING,
    SORT_ORDER NUMBER DEFAULT 0,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY STRING,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ENUMERATION_ID)
)
COMMENT = 'Enumerated values for business attributes';

-- Links table columns to global attributes
CREATE TABLE IF NOT EXISTS CATALOG_DB.CATALOG_SCHEMA.COLUMN_ATTRIBUTES (
    LINK_ID STRING DEFAULT UUID_STRING(),
    TABLE_FULL_NAME STRING NOT NULL,
    COLUMN_NAME STRING NOT NULL,
    ATTRIBUTE_NAME STRING NOT NULL,
    LINKED_BY STRING,
    LINKED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (LINK_ID)
)
COMMENT = 'Links table columns to global business attributes';

-- Change request workflow for content changes (descriptions, tags, enumerations)
CREATE TABLE IF NOT EXISTS CATALOG_DB.CATALOG_SCHEMA.CHANGE_REQUESTS (
    REQUEST_ID STRING DEFAULT UUID_STRING(),
    REQUEST_TYPE STRING NOT NULL,
    TARGET_OBJECT STRING NOT NULL,
    REQUESTER STRING NOT NULL,
    JUSTIFICATION STRING NOT NULL,
    PROPOSED_CHANGE VARIANT,
    CURRENT_VALUE VARIANT,
    STATUS STRING DEFAULT 'pending',
    ASSIGNED_TO STRING,
    APPROVER STRING,
    DECISION_DATE TIMESTAMP_NTZ,
    DECISION_COMMENT STRING,
    REQUESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (REQUEST_ID)
)
COMMENT = 'Change request workflow for descriptions, tags, and enumerations';

-- ============================================================================
-- CONTACTS TABLE
-- ============================================================================

-- Table to store contact information for tables (Owner, Steward, Domain Expert)
CREATE TABLE IF NOT EXISTS CATALOG_DB.CATALOG_SCHEMA.CATALOG_CONTACTS (
    CONTACT_ID STRING DEFAULT UUID_STRING(),
    FULL_TABLE_NAME STRING NOT NULL,
    PURPOSE STRING NOT NULL,  -- DATA_OWNER, STEWARD, DOMAIN_EXPERT, etc.
    METHOD STRING NOT NULL,   -- Email, username, or other contact method
    CREATED_BY STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY STRING,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CONTACT_ID),
    UNIQUE (FULL_TABLE_NAME, PURPOSE)
)
COMMENT = 'Contact information for datasets (owners, stewards, domain experts)';

-- ============================================================================
-- DATA PRODUCT TAG
-- ============================================================================

-- Create a Snowflake tag for Data Products (to group related tables/views)
CREATE TAG IF NOT EXISTS CATALOG_DB.CATALOG_SCHEMA.DATA_PRODUCT
  COMMENT = 'Tag to group tables and views into logical Data Products';

-- ============================================================================
-- POPULARITY AND TRACKING TABLES
-- ============================================================================

-- Table to track dataset popularity (views/accesses)
CREATE TABLE IF NOT EXISTS CATALOG_DB.CATALOG_SCHEMA.TABLE_POPULARITY (
    TABLE_FULL_NAME STRING NOT NULL,
    VIEW_COUNT NUMBER DEFAULT 0,
    LAST_VIEWED TIMESTAMP_NTZ,
    UNIQUE_VIEWERS NUMBER DEFAULT 0,
    PRIMARY KEY (TABLE_FULL_NAME)
)
COMMENT = 'Dataset popularity metrics';

-- Table for user-defined tags
CREATE TABLE IF NOT EXISTS CATALOG_DB.CATALOG_SCHEMA.TABLE_TAGS (
    TAG_ID STRING DEFAULT UUID_STRING(),
    TABLE_FULL_NAME STRING NOT NULL,
    TAG_NAME STRING NOT NULL,
    CREATED_BY STRING NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (TAG_ID)
)
COMMENT = 'User-defined tags for datasets';

-- Table for lineage information
CREATE TABLE IF NOT EXISTS CATALOG_DB.CATALOG_SCHEMA.TABLE_LINEAGE (
    LINEAGE_ID STRING DEFAULT UUID_STRING(),
    SOURCE_TABLE STRING NOT NULL,
    TARGET_TABLE STRING NOT NULL,
    LINEAGE_TYPE STRING NOT NULL,
    DISCOVERED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (LINEAGE_ID)
)
COMMENT = 'Data lineage relationships between tables';

-- ============================================================================
-- ENRICHED VIEWS
-- ============================================================================

-- Create enriched view combining metadata with user content
CREATE OR REPLACE VIEW CATALOG_DB.CATALOG_SCHEMA.ENRICHED_CATALOG AS
SELECT 
    m.DATABASE_NAME,
    m.SCHEMA_NAME,
    m.TABLE_NAME,
    m.DATABASE_NAME || '.' || m.SCHEMA_NAME || '.' || m.TABLE_NAME as FULL_TABLE_NAME,
    m.TABLE_TYPE,
    m.ROW_COUNT,
    m.BYTES,
    ROUND(m.BYTES / 1024.0 / 1024.0 / 1024.0, 2) as SIZE_GB,
    m.CREATED,
    m.LAST_ALTERED,
    m.COMMENT as SYSTEM_COMMENT,
    d.USER_DESCRIPTION,
    d.LAST_UPDATED_BY as DESCRIPTION_AUTHOR,
    d.UPDATED_AT as DESCRIPTION_UPDATED,
    COALESCE(AVG(r.RATING), 0) as AVG_RATING,
    COUNT(DISTINCT r.USER_NAME) as RATING_COUNT,
    COUNT(DISTINCT c.COMMENT_ID) as COMMENT_COUNT,
    COALESCE(p.VIEW_COUNT, 0) as VIEW_COUNT,
    COALESCE(p.UNIQUE_VIEWERS, 0) as UNIQUE_VIEWERS,
    p.LAST_VIEWED,
    m.CACHED_AT
FROM CATALOG_DB.CATALOG_SCHEMA.CATALOG_METADATA m
LEFT JOIN CATALOG_DB.CATALOG_SCHEMA.TABLE_DESCRIPTIONS d 
    ON m.DATABASE_NAME || '.' || m.SCHEMA_NAME || '.' || m.TABLE_NAME = d.TABLE_FULL_NAME
LEFT JOIN CATALOG_DB.CATALOG_SCHEMA.USER_RATINGS r 
    ON m.DATABASE_NAME || '.' || m.SCHEMA_NAME || '.' || m.TABLE_NAME = r.TABLE_FULL_NAME
LEFT JOIN CATALOG_DB.CATALOG_SCHEMA.USER_COMMENTS c 
    ON m.DATABASE_NAME || '.' || m.SCHEMA_NAME || '.' || m.TABLE_NAME = c.TABLE_FULL_NAME
LEFT JOIN CATALOG_DB.CATALOG_SCHEMA.TABLE_POPULARITY p
    ON m.DATABASE_NAME || '.' || m.SCHEMA_NAME || '.' || m.TABLE_NAME = p.TABLE_FULL_NAME
GROUP BY 
    m.DATABASE_NAME, m.SCHEMA_NAME, m.TABLE_NAME, m.TABLE_TYPE,
    m.ROW_COUNT, m.BYTES, m.CREATED, m.LAST_ALTERED, m.COMMENT,
    d.USER_DESCRIPTION, d.LAST_UPDATED_BY, d.UPDATED_AT, m.CACHED_AT,
    p.VIEW_COUNT, p.UNIQUE_VIEWERS, p.LAST_VIEWED;

-- Note: In a real deployment, you would need to grant USAGE on all existing databases
-- This script provides a template - execute these grants as ACCOUNTADMIN for each database:
-- GRANT USAGE ON DATABASE <database_name> TO ROLE SYSADMIN;
-- GRANT USAGE ON ALL SCHEMAS IN DATABASE <database_name> TO ROLE SYSADMIN;
-- GRANT SELECT ON ALL TABLES IN DATABASE <database_name> TO ROLE SYSADMIN;
-- GRANT SELECT ON ALL VIEWS IN DATABASE <database_name> TO ROLE SYSADMIN;
-- GRANT SELECT ON FUTURE TABLES IN DATABASE <database_name> TO ROLE SYSADMIN;
-- GRANT SELECT ON FUTURE VIEWS IN DATABASE <database_name> TO ROLE SYSADMIN;

-- ============================================================================
-- INITIAL METADATA POPULATION PROCEDURE
-- ============================================================================

-- Create procedure to refresh catalog metadata
CREATE OR REPLACE PROCEDURE CATALOG_DB.CATALOG_SCHEMA.REFRESH_CATALOG_METADATA()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    -- Clear existing metadata
    DELETE FROM CATALOG_DB.CATALOG_SCHEMA.CATALOG_METADATA;
    
    -- Populate from all accessible databases
    INSERT INTO CATALOG_DB.CATALOG_SCHEMA.CATALOG_METADATA (
        DATABASE_NAME, SCHEMA_NAME, TABLE_NAME, TABLE_TYPE,
        ROW_COUNT, BYTES, CREATED, LAST_ALTERED, COMMENT
    )
    SELECT 
        TABLE_CATALOG as DATABASE_NAME,
        TABLE_SCHEMA as SCHEMA_NAME,
        TABLE_NAME,
        TABLE_TYPE,
        ROW_COUNT,
        BYTES,
        CREATED,
        LAST_ALTERED,
        COMMENT
    FROM SNOWFLAKE.ACCOUNT_USAGE.TABLES
    WHERE TABLE_SCHEMA != 'INFORMATION_SCHEMA'
      AND TABLE_CATALOG != 'SNOWFLAKE'
      AND DELETED IS NULL;
    
    -- Clear existing column metadata
    DELETE FROM CATALOG_DB.CATALOG_SCHEMA.CATALOG_COLUMNS;
    
    -- Populate column metadata
    INSERT INTO CATALOG_DB.CATALOG_SCHEMA.CATALOG_COLUMNS (
        FULL_TABLE_NAME, COLUMN_NAME, DATA_TYPE,
        IS_NULLABLE, COMMENT, ORDINAL_POSITION
    )
    SELECT 
        TABLE_CATALOG || '.' || TABLE_SCHEMA || '.' || TABLE_NAME as FULL_TABLE_NAME,
        COLUMN_NAME,
        DATA_TYPE,
        IS_NULLABLE,
        COMMENT,
        ORDINAL_POSITION
    FROM SNOWFLAKE.ACCOUNT_USAGE.COLUMNS
    WHERE TABLE_SCHEMA != 'INFORMATION_SCHEMA'
      AND TABLE_CATALOG != 'SNOWFLAKE'
      AND DELETED IS NULL;
    
    RETURN 'Catalog metadata refreshed successfully';
END;
$$;

-- ============================================================================
-- VERIFY SETUP
-- ============================================================================

SELECT 'Data Catalog Database created successfully' as status;
SELECT 'Tables created: CATALOG_METADATA, CATALOG_COLUMNS, USER_RATINGS, USER_COMMENTS, TABLE_DESCRIPTIONS, ACCESS_REQUESTS, ROLE_PERMISSIONS, CATALOG_CONTACTS, ATTRIBUTE_DEFINITIONS, ATTRIBUTE_ENUMERATIONS, COLUMN_ATTRIBUTES, CHANGE_REQUESTS, TABLE_POPULARITY, TABLE_TAGS, TABLE_LINEAGE' as tables;

-- ============================================================================
-- SERVICE ROLE GRANTS
-- ============================================================================

-- Grant full access on all catalog tables to CATALOG_SERVICE_ROLE
GRANT ALL ON ALL TABLES IN SCHEMA CATALOG_DB.CATALOG_SCHEMA TO ROLE CATALOG_SERVICE_ROLE;
GRANT ALL ON ALL VIEWS IN SCHEMA CATALOG_DB.CATALOG_SCHEMA TO ROLE CATALOG_SERVICE_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA CATALOG_DB.CATALOG_SCHEMA TO ROLE CATALOG_SERVICE_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA CATALOG_DB.CATALOG_SCHEMA TO ROLE CATALOG_SERVICE_ROLE;

-- Grant usage on schema and database
GRANT USAGE ON DATABASE CATALOG_DB TO ROLE CATALOG_SERVICE_ROLE;
GRANT USAGE ON SCHEMA CATALOG_DB.CATALOG_SCHEMA TO ROLE CATALOG_SERVICE_ROLE;

-- Grant APPLY TAG privilege for the DATA_PRODUCT tag
GRANT APPLY ON TAG CATALOG_DB.CATALOG_SCHEMA.DATA_PRODUCT TO ROLE CATALOG_SERVICE_ROLE;

-- Show current configuration
SELECT CURRENT_DATABASE() as database_name, 
       CURRENT_SCHEMA() as schema_name,
       CURRENT_ROLE() as role_name,
       CURRENT_WAREHOUSE() as warehouse_name;

-- Run initial metadata refresh
CALL CATALOG_DB.CATALOG_SCHEMA.REFRESH_CATALOG_METADATA();

-- Show statistics
SELECT COUNT(*) as total_tables FROM CATALOG_DB.CATALOG_SCHEMA.CATALOG_METADATA;
SELECT COUNT(*) as total_columns FROM CATALOG_DB.CATALOG_SCHEMA.CATALOG_COLUMNS;
SELECT COUNT(DISTINCT DATABASE_NAME) as databases_scanned FROM CATALOG_DB.CATALOG_SCHEMA.CATALOG_METADATA;

