-- Update ACCESS_REQUESTS table to add new fields for enhanced workflow
USE SCHEMA CATALOG_DB.CATALOG_SCHEMA;

-- Add new columns to ACCESS_REQUESTS table
ALTER TABLE IF EXISTS ACCESS_REQUESTS 
ADD COLUMN IF NOT EXISTS ACCESS_START_DATE DATE;

ALTER TABLE IF EXISTS ACCESS_REQUESTS 
ADD COLUMN IF NOT EXISTS ACCESS_END_DATE DATE;

ALTER TABLE IF EXISTS ACCESS_REQUESTS 
ADD COLUMN IF NOT EXISTS ACCESS_TYPE STRING DEFAULT 'ROLE' 
COMMENT 'ROLE or USER based access';

ALTER TABLE IF EXISTS ACCESS_REQUESTS 
ADD COLUMN IF NOT EXISTS GRANT_TO_NAME STRING 
COMMENT 'Role name or User name depending on ACCESS_TYPE';

ALTER TABLE IF EXISTS ACCESS_REQUESTS 
ADD COLUMN IF NOT EXISTS ASSIGNED_TO STRING 
COMMENT 'Admin user assigned to review this request';

ALTER TABLE IF EXISTS ACCESS_REQUESTS 
ADD COLUMN IF NOT EXISTS ADDITIONAL_INFO STRING 
COMMENT 'Additional information requested from user';

-- Update the enriched catalog view to include contacts information
CREATE OR REPLACE VIEW CATALOG_DB.CATALOG_SCHEMA.ENRICHED_CATALOG AS
SELECT
    m.DATABASE_NAME, 
    m.SCHEMA_NAME, 
    m.TABLE_NAME, 
    m.DATABASE_NAME || '.' || m.SCHEMA_NAME || '.' || m.TABLE_NAME as FULL_TABLE_NAME, 
    m.TABLE_TYPE, 
    m.ROW_COUNT, 
    m.BYTES, 
    ROUND(m.BYTES / 1024.0 / 1024.0 / 1024.0, 2) as SIZE_GB, 
    m.CREATED, 
    m.LAST_ALTERED, 
    m.COMMENT as SYSTEM_COMMENT,
    d.USER_DESCRIPTION, 
    d.LAST_UPDATED_BY as DESCRIPTION_AUTHOR, 
    d.UPDATED_AT as DESCRIPTION_UPDATED,
    COALESCE(AVG(r.RATING), 0) as AVG_RATING, 
    COUNT(DISTINCT r.USER_NAME) as RATING_COUNT, 
    COUNT(DISTINCT c.COMMENT_ID) as COMMENT_COUNT,
    COALESCE(p.VIEW_COUNT, 0) as VIEW_COUNT, 
    COALESCE(p.UNIQUE_VIEWERS, 0) as UNIQUE_VIEWERS, 
    p.LAST_VIEWED,
    m.CACHED_AT
FROM CATALOG_DB.CATALOG_SCHEMA.CATALOG_METADATA m
LEFT JOIN CATALOG_DB.CATALOG_SCHEMA.TABLE_DESCRIPTIONS d 
    ON m.DATABASE_NAME || '.' || m.SCHEMA_NAME || '.' || m.TABLE_NAME = d.TABLE_FULL_NAME
LEFT JOIN CATALOG_DB.CATALOG_SCHEMA.USER_RATINGS r 
    ON m.DATABASE_NAME || '.' || m.SCHEMA_NAME || '.' || m.TABLE_NAME = r.TABLE_FULL_NAME
LEFT JOIN CATALOG_DB.CATALOG_SCHEMA.USER_COMMENTS c 
    ON m.DATABASE_NAME || '.' || m.SCHEMA_NAME || '.' || m.TABLE_NAME = c.TABLE_FULL_NAME
LEFT JOIN CATALOG_DB.CATALOG_SCHEMA.TABLE_POPULARITY p 
    ON m.DATABASE_NAME || '.' || m.SCHEMA_NAME || '.' || m.TABLE_NAME = p.TABLE_FULL_NAME
GROUP BY 
    m.DATABASE_NAME, m.SCHEMA_NAME, m.TABLE_NAME, m.TABLE_TYPE, m.ROW_COUNT, m.BYTES, 
    m.CREATED, m.LAST_ALTERED, m.COMMENT, d.USER_DESCRIPTION, d.LAST_UPDATED_BY, 
    d.UPDATED_AT, m.CACHED_AT, p.VIEW_COUNT, p.UNIQUE_VIEWERS, p.LAST_VIEWED;

SELECT 'Schema update completed successfully' as STATUS;
